codecov:
  token: "3f9f46af-7e33-48eb-afa3-a6ee04b32cbd"
  bot: "codecov-io"
  ci:
    - "https://travis-ci.com/github/Allen0929/codecovSimple"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
